# Generated by Django 4.1 on 2022-08-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_newuser_post_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messageUser',
            new_name='author',
        ),
    ]
