# Generated by Django 4.1 on 2022-08-11 15:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_messageuser_message_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messagePost',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(default=None, upload_to='upload/'),
        ),
    ]
