# Generated by Django 4.1 on 2022-08-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_message_text_alter_message_text_en_us_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
    ]
